# Site settings
title: Personal Webpage
email: skurekjakub@gmail.com
email_short: skurekjakub
description: > # this means to ignore newlines until "baseurl:"
 Creative is a one page Bootstrap theme for creatives, small businesses, and other multipurpose uses.
 The theme includes a number of rich features and plugins that you can use as a great boilerplate for your next Jekyll project!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "skurekjakub.github.io" # the base hostname & protocol for your site

twitter_username: skurekjakub
github_username:  skurekjakub
linkedin_username: skurekjakub
muni_username:    skurekjakub

# Build settings
markdown: kramdown
